name: Release

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

concurrency: release

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.14.0]
        pnpm-version: [10.7.0]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.4.10
        with:
          publish: pnpm publish -r --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
